# Generated by Django 4.1 on 2022-09-29 11:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import gestionProyectoApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackLog',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(default='', max_length=200)),
                ('idBackLog', models.IntegerField(default=gestionProyectoApp.models.BackLog.generarIdBackLog, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'BackLog',
                'db_table': 'BackLog',
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('idFormulario', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Formulario',
                'db_table': 'Formulario',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(default='', max_length=200)),
                ('idPermiso', models.IntegerField(default=gestionProyectoApp.models.Permiso.generarIdPermisos, primary_key=True, serialize=False)),
                ('tipo', models.CharField(default='', max_length=1)),
                ('formulario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionProyectoApp.formulario')),
            ],
            options={
                'verbose_name': 'Permiso',
                'db_table': 'Permiso',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('idProyecto', models.IntegerField(default=gestionProyectoApp.models.Proyecto.generarIdProyecto, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'db_table': 'Proyecto',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(default='', max_length=200)),
                ('idRol', models.IntegerField(default=gestionProyectoApp.models.Rol.generarIdRol, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Rol',
                'db_table': 'Rol',
            },
        ),
        migrations.CreateModel(
            name='SprintBackLog',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(default='', max_length=200)),
                ('idSprintBackLog', models.IntegerField(default=gestionProyectoApp.models.SprintBackLog.generarId, primary_key=True, serialize=False)),
                ('backLog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionProyectoApp.backlog')),
            ],
            options={
                'verbose_name': 'SprintBackLog',
                'db_table': 'SprintBackLog',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Usuario',
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='UsuariosRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDesde', models.DateField(default=django.utils.timezone.now, null=True)),
                ('fechaHasta', models.DateField(default=None, null=True)),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_roles', to='gestionProyectoApp.rol')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_roles', to='gestionProyectoApp.usuario')),
            ],
            options={
                'verbose_name': 'UsuariosRoles',
                'db_table': 'UsuariosRoles',
            },
        ),
        migrations.CreateModel(
            name='UsuariosProyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_proyectos', to='gestionProyectoApp.proyecto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_proyectos', to='gestionProyectoApp.usuario')),
            ],
            options={
                'verbose_name': 'UsuariosProyectos',
                'db_table': 'UsuariosProyectos',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='proyectos',
            field=models.ManyToManyField(related_name='usuario_proyecto', through='gestionProyectoApp.UsuariosProyectos', to='gestionProyectoApp.proyecto'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='roles',
            field=models.ManyToManyField(related_name='usuario_rol', through='gestionProyectoApp.UsuariosRoles', to='gestionProyectoApp.rol'),
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(default='', max_length=200)),
                ('idUserStory', models.IntegerField(default=gestionProyectoApp.models.UserStory.generarIdUserStory, primary_key=True, serialize=False)),
                ('sprintBackLog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionProyectoApp.sprintbacklog')),
            ],
            options={
                'verbose_name': 'UserStory',
                'db_table': 'UserStory',
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(default='', max_length=200)),
                ('idSprint', models.IntegerField(default=gestionProyectoApp.models.Sprint.generarId, primary_key=True, serialize=False)),
                ('sprintBackLog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionProyectoApp.sprintbacklog')),
            ],
            options={
                'verbose_name': 'Sprint',
                'db_table': 'Sprint',
            },
        ),
        migrations.CreateModel(
            name='RolesPermisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_permisos', to='gestionProyectoApp.permiso')),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_permisos', to='gestionProyectoApp.rol')),
            ],
            options={
                'verbose_name': 'RolesPermisos',
                'db_table': 'RolesPermisos',
            },
        ),
        migrations.AddField(
            model_name='rol',
            name='permisos',
            field=models.ManyToManyField(related_name='rol_permiso', through='gestionProyectoApp.RolesPermisos', to='gestionProyectoApp.permiso'),
        ),
        migrations.AddField(
            model_name='backlog',
            name='proyecto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionProyectoApp.proyecto'),
        ),
    ]
