# Generated by Django 4.1 on 2022-10-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProyectoApp', '0002_userstory_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprintbacklog',
            name='estado',
            field=models.CharField(default='Por hacer', max_length=12),
        ),
    ]
