# Generated by Django 4.1 on 2022-10-08 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProyectoApp', '0003_sprintbacklog_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprintbacklog',
            name='duracion',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='sprintbacklog',
            name='fechaFin',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='sprintbacklog',
            name='fechaInicio',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
