# Generated by Django 4.1 on 2022-10-08 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProyectoApp', '0004_sprintbacklog_duracion_sprintbacklog_fechafin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprintbacklog',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='sprintbacklog',
            name='fechaFin',
        ),
        migrations.RemoveField(
            model_name='sprintbacklog',
            name='fechaInicio',
        ),
    ]
