# Generated by Django 4.1 on 2022-08-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionProyectoApp', '0006_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='idFormulario',
        ),
        migrations.AddField(
            model_name='rol',
            name='formulario',
            field=models.ManyToManyField(related_name='rol_permiso', to='gestionProyectoApp.permiso'),
        ),
    ]
